#If the shape switcher menu should be scrolling or static
scrolling = true
#If the change block shape key should be held or toggled to open the menu
#Allowed Values: HOLD, TOGGLE, PRESS
hold = "HOLD"
